name: Build Gradle project

on: [push, pull_request]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup jfrog credentials
        env:
          JFROG_RO_COMMUNITY_USER: ${{ secrets.JFROG_RO_COMMUNITY_USER }}
          JFROG_RO_COMMUNITY_PASSWORD: ${{ secrets.JFROG_RO_COMMUNITY_PASSWORD }}
        run: |
            echo genesisArtifactoryUser=${JFROG_RO_COMMUNITY_USER} > ./server/jvm/gradle.properties \
            echo genesisArtifactoryPassword="${JFROG_RO_COMMUNITY_PASSWORD} > ./server/jvm/gradle.properties \

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build --info